-- MySQL Script generated by MySQL Workbench
-- Wed Aug 26 09:42:36 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema alerta_ciudadana_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alerta_ciudadana_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alerta_ciudadana_db` ;
USE `alerta_ciudadana_db` ;

-- -----------------------------------------------------
-- Table `alerta_ciudadana_db`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alerta_ciudadana_db`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único y clave primaria del ciclista en el sistema.',
  `nombre` VARCHAR(45) NOT NULL COMMENT 'Nombre completo o usuario visible de la persona',
  `celular` VARCHAR(15) NULL DEFAULT NULL COMMENT 'Número telefónico para contacto directo o autenticación vía SMS.',
  `email` VARCHAR(100) NOT NULL COMMENT 'Correo electrónico del usuario para login y notificaciones.',
  `password_hash` VARCHAR(255) NOT NULL COMMENT 'Cadena encriptada/hasheada para la seguridad de la contraseña.',
  `tipo_bicicleta` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Tipo o categoría de la bicicleta (p. ej., urbana, de ruta, MTB, eléctrica) para personalizar recomendaciones.',
  UNIQUE INDEX (`email` ASC) VISIBLE,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alerta_ciudadana_db`.`ContactoEmergencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alerta_ciudadana_db`.`ContactoEmergencia` (
  `idContacto` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del contacto de emergencia.',
  `nombre_contacto` VARCHAR(45) NOT NULL COMMENT 'Nombre de la persona a notificar en caso de un incidente.',
  `telefono` VARCHAR(15) NOT NULL COMMENT 'Número de teléfono al que se enviarán alertas o llamadas de auxilio.',
  `parentesco` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Relación con el usuario (ej. familiar, amigo, pareja).',
  `Usuario_idUsuario` INT NOT NULL COMMENT 'Clave foránea que asocia este contacto con un usuario específico.',
  PRIMARY KEY (`idContacto`),
  INDEX `fk_ContactoEmergencia_Usuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_ContactoEmergencia_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `alerta_ciudadana_db`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alerta_ciudadana_db`.`AlertaCiudadana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alerta_ciudadana_db`.`AlertaCiudadana` (
  `idAlerta` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único de la alerta comunitaria.',
  `tipo_alerta` VARCHAR(45) NOT NULL COMMENT 'Tipo de aviso o peligro detectado (ej. zona insegura, baja iluminación).',
  `descripcion` VARCHAR(200) NULL DEFAULT NULL COMMENT 'Detalle explicativo proporcionado por el usuario sobre la alerta.',
  `latitud` DECIMAL(10,8) NOT NULL COMMENT 'Coordenada de latitud del lugar del reporte.',
  `longitud` DECIMAL(11,8) NOT NULL COMMENT 'Coordenada de longitud del lugar del reporte.',
  `fecha_hora` DATETIME NOT NULL COMMENT 'Momento exacto en que se generó la alerta.',
  `estado_validacion` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Estado de verificación comunitaria o del sistema (ej. pendiente, confirmada, resuelta).',
  `Usuario_idUsuario` INT NOT NULL COMMENT 'Clave foránea que asocia la alerta con el usuario emisor.',
  PRIMARY KEY (`idAlerta`),
  INDEX `fk_AlertaCiudadana_Usuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_AlertaCiudadana_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `alerta_ciudadana_db`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alerta_ciudadana_db`.`Ruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alerta_ciudadana_db`.`Ruta` (
  `idRuta` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del recorrido registrado.',
  `origen_lat` DECIMAL(10,8) NOT NULL COMMENT 'Latitud geográfica del punto de inicio del trayecto.',
  `origen_lng` DECIMAL(11,8) NOT NULL COMMENT 'Longitud geográfica del punto de inicio.',
  `destino_lat` DECIMAL(10,8) NOT NULL COMMENT 'Latitud geográfica del punto final o destino.',
  `destino_lng` DECIMAL(11,8) NOT NULL COMMENT 'Longitud geográfica del punto final.',
  `distancia_km` FLOAT NULL DEFAULT NULL COMMENT 'Distancia total recorrida estimada o real expresada en kilómetros.',
  `fecha_ruta` DATETIME NOT NULL COMMENT 'Marca de tiempo que registra cuándo se realizó o guardó el recorrido.',
  `Usuario_idUsuario` INT NOT NULL COMMENT 'Clave foránea que relaciona la ruta con el usuario que la realizó.',
  PRIMARY KEY (`idRuta`),
  INDEX `fk_Ruta_Usuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Ruta_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `alerta_ciudadana_db`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alerta_ciudadana_db`.`INCIDENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alerta_ciudadana_db`.`INCIDENTE` (
  `id_incidente` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del evento o reporte de seguridad.',
  `tipo_incidente` VARCHAR(45) NOT NULL COMMENT 'Categorización del suceso (ej. robo, accidente, vía dañada, acoso).',
  `coordenadas` GEOMETRY NOT NULL COMMENT 'Objeto de datos espaciales con la ubicación exacta (punto o trazado) donde ocurrió el evento.',
  `Usuario_idUsuario` INT NOT NULL COMMENT 'Clave foránea del usuario que reportó el incidente.',
  PRIMARY KEY (`id_incidente`),
  INDEX `fk_INCIDENTE_Usuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_INCIDENTE_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `alerta_ciudadana_db`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
